### ISSUE TITLE
Download the BodoRuckhauerDVSOpticalFlowData

### ISSUE THREAD

**Issue by LuLu0616** [SensorsINI/jaer#15]
When I download the BodoRuckhauerDVSOpticalFlowData, I meet some trouble which the data need authorization in Sync. Is there another way to download the data?

**Comment by tobidelbruck** [comment]
Unfortunately no. You have to just wait until the sharing is approved. Sorry about that. When I get back to Zurich I will check on it. Maybe the link aged. 
-- 
Tobi Delbruck, www.ini.uzh.ch/~ tobi, Swiss cell +41766291500, USA cell +16265102646

**Comment by askanki** [comment]
Hi,

I am trying to download the dataset but the link is not responding. Is there any other way I can download the dataset?

Thanks in advance.

Regards,
Ankit

**Comment by tobidelbruck** [comment]
It's possible it got hit by Qlocker ransomware, will check it. We got hit, but we have the files on other machines.
Thanks
-- 
Tobi Delbruck, www.ini.uzh.ch/~ tobi, Swiss cell +41766291500, USA cell +16265102646

**Comment by askanki** [comment]
Thanks Prof. Tobi. That will be very helpful.

**Comment by tobidelbruck** [comment]
Yes, that folder got hit by QLocker, am restoring files from backup. Np, 
thanks for asking about it.

**Comment by tobidelbruck** [comment]
I restored all the available files alongside the encypted .7z files left 
by Qlocker. If you cannot sync, try this share link:

https://link.resilio.com/#f=BodoRuckhauerDVSOpticalFlowData&sz=32E8&t=1&s=GUXFTJAUSOTOPMS7PCN4USVEUZ4I7PUM&i=C7Y6JJHAGBN5CGSDKGNE3DLJ4SHRCFNFY&e=1621952442&v=2.7&a=2

**Comment by askanki** [comment]
Thanks Prof. Tobi for fixing the link. I am able to access now. folders are syncing.
