### ISSUE TITLE
New SPI commands remote break compilation

### ISSUE THREAD

**Issue by ghost** [SensorsINI/jaer#22]
When I attempt to compile the new code with ant, I get the following error:

MultiBitConfigRegister is not abstract and does not override abstract method processRemoteControlCommand(RemoteControlCommand, String) in RemoteControlled

**Comment by tobidelbruck** [comment]
My bad, I will check and fix this problem later today. Sorry about this. 
Result of adding a new remote control command.

**Comment by tobidelbruck** [comment]
Pushed  fix for this build problem. Solution for setting MultiBitValue 
register not yet tested but this push should fix the build problem. 
Sorry about not checking clean build.

**Comment by tobidelbruck** [comment]
Issue fixed apparently
