### ISSUE TITLE
No response and stopped in the starting picture

### ISSUE THREAD

**Issue by Rainyfish** [SensorsINI/jaer#28]
Hi,
    I tried many times to fix the environment of JVM, but jaer still had no response  and stopped in its starting picture. And the last comments appeared in picture is "Starting with no arguments in working directory = ." Windows 64 bit
   Looking forward to your reply.

**Comment by tobidelbruck** [comment]
Did you watch YouTube setup video? Are you using jdk 1.8 ? Jdk 10 is not so tested. Please provide more details. 
Sorry this is from phone.

**Comment by Rainyfish** [comment]
Thank you for your reply. I watched the setup video and the user guide.  I used JDK 1.8. Does the jaer need some special configs. The jaer works well in another computer. But it cannot run in other two computer even I used the same configs.

**Comment by tobidelbruck** [comment]
Cause unknown, suggest to try bundled install4j installer which comes with Java JDK bundled.
