### ISSUE TITLE
Step backwards again, step forward, play forward etc. (using master branch)

### ISSUE THREAD

**Issue by julio-guillen** [SensorsINI/jaer#32]
Hi!,

I've used the new STEP BACKWARDS function in order to analyze data quite successfully in recent days. But I think i found what may be more bugs.

1) When  you STEP FORWARD and then press PLAY, video will play forward. If you STEP BACKWARDS and press play, it will play backwards. Not sure if this is a feature, but it happens even if you press PLAY FORWARD.

2) PLAY BACKWARDS does not work as intended and plays forward. So a workaround for people who wants this feature can be using the STEP BACKWARDS approach described in 1.

3) I've notices that if loged data does not have events for a period of time, STEP FORWARD wont advance in time. I have created a video so you can see the error. File is CarsPassingUnderBridge.dat where in 18918390 (time in us) you dont gete events for a period of time, so STEP FORWARD does not advance in time.

You can check a video here:
https://pasteboard.co/JgTRUf6.gif

Thanks in advance. Love jAER :)

**Comment by tobidelbruck** [comment]
seems fixed except at start/end of recording, could be more ergonomic to not be stuck in reverse at start of recording. Also probably should not loop recording when jogging
