### ISSUE TITLE
how to cite?

### ISSUE THREAD

**Issue by ChiaraBartolozzi** [SensorsINI/jaer#33]
Hi @tobidelbruck 

how can I cite the jAER project? do you have a bibtex citation?

Thanks
Chiara

**Comment by julio-guillen** [comment]
Hi,

I've seen jAER cited both as bibliography and in text. 

For example, in lichsteiner2008, jAER is cited as:

> jAER Open Source Project. 2007 [Online]. Available: http://jaer.wiki. sourceforge.net

Tobi cited jAER in delbruck2013 as:

> (2007). jAER Open Source Project: Real Time Sensory-Motor Processing for EventBased Sensors and Systems. Available online at: http://www.jaerproject.org

In brandli2014, Hu2016 they just cite jAER in text as:

> software project jAER (www.jaerproject.org)

Hope it helps :)
