### ISSUE TITLE
can't build jaer on netbeans ide, verification always needed

### ISSUE THREAD

**Issue by lin88619973** [SensorsINI/jaer#40]
after clicking clean and build， it Pop up a dialog box just like this
verification needed
                  artifactory realm
username：
passport：

**Comment by tobidelbruck** [comment]
It must be something to do with pulling the libraries using ivy from 
maven-central repository. I don't know the underlying cause and have not 
seen this particular problem.

Does it continue if you just enter null user and password?  Can you 
google maven-central / ivy authentication bug? What is the detailed 
logging output shown in the console?

**Comment by lin88619973** [comment]
Thank you for your reply, I am using the 1.5 version of the platform recently, and it can be built normally. The version I currently use can meet my needs, and I will try your suggestions when I am free. Thanks again.

**Comment by julio-guillen** [comment]
I have the same issue. It's kind of annoying, as even when trying to delete the project, it still launches the user/password dialog box.

I've tried both version 19.5 and master versions with same results.

![image](https://user-images.githubusercontent.com/25005788/126470050-1d95b318-d39e-4d51-a77a-d8dbe141b85f.png)

**Comment by tobidelbruck** [comment]
Did I post solution to this?  I think it requires you to have a valid 
github token stored. But I might not be correct about my memory of this. 
It is some arcane thing related to access to the Maven repos for all the 
libraries.

**Comment by julio-guillen** [comment]
Hi, thank you for the fast response.

Do you mean this [1] post?

[1] https://groups.google.com/g/jaer-users/c/nFIGoXOrO5Y/m/mhO2rDDaAwAJ

**Comment by julio-guillen** [comment]
Hi,

Version 1.7.5 builds correctly.
Version 1.8.1.8 builds correctly.

Version 1.9.0 and greater requires authentication.

Regards

**Comment by julio-guillen** [comment]
Hi,

If you constantly cancel each time Artifactory Realm dialog box shows, you will eventually be able to clean & build jAER. Kind of annoying, but it works.

Thanks

**Comment by tobidelbruck** [comment]
Is your ivysettings.xml the same as HEAD version? I recall changing this 
line marked below to deal with this headache

  <credentials host="SERVER" realm="Artifactory Realm" username="USER" 
passwd="PASSWORD" />

**Comment by tobidelbruck** [comment]
No, that post was for the post-tag release generation mechanism....

**Comment by julio-guillen** [comment]
Hi,

Im using right now cloned version so ivysettings.xml contains that line. I've checked some of 1.9.x releases and they dont. So I guess that wont fix the issue.

Regards

**Comment by tobidelbruck** [comment]
Do you have a stored github token?

**Comment by tobidelbruck** [comment]
I.e. did you use the Netbeans Team/Remote/Fetch.... menu to store a 
login via token to github?

https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by julio-guillen** [comment]
Hi 

I just used git clone from command line. Ive tried Netbeans Team, using both a PAT and my own user/password, but same luck.

Sorry for all the trouble...

**Comment by cargonriv** [comment]
Hello, 

I had the same issue for about a week while trying to build jAER on NB as well. It seems that adding a GlassFish server on your local domain seems to fix the problem for me. You can find the server's dialog box on the Tools tab under 'Servers'. I used the default localhost and ports, but I did add a username and password of my own. 

Hope this helps.
