### ISSUE TITLE
Measure the time of a filter

### ISSUE THREAD

**Issue by shirleyatgithub** [SensorsINI/jaer#41]
Dear Tobi,
In the recording "Tracking cars with a dynamic vision sensor" (https://www.youtube.com/watch?v=4mKlVUz7EIY), I wonder how to measure the cost of time applying the tracker.
I remember you have mentioned there is a time measurement in the jAER. But I didn't find it in the document.
Looking forward to your reply. @tobidelbruck 
Best regards.
Shasha Guo

**Comment by tobidelbruck** [comment]
Timing is measured using the FilterFrame menu item... see the user guide
