### ISSUE TITLE
JAER problem with the EVK4 camera outputs

### ISSUE THREAD

**Issue by azemrani** [SensorsINI/jaer#48]
I am trying to use JAER for an event-based camera (EVK4) to perform noise reduction. However, when I open the sample dat files of this camera (https://docs.prophesee.ai/stable/datasets.html) using jAER, it does not show anything and didn’t work. 

![jaer](https://github.com/SensorsINI/jaer/assets/157007816/a76a6316-c140-40e2-8aab-fd3d34f20741)

**Comment by wzygzlm** [comment]
Hi,

jAER hasn't supported the Prophesee cameras and its data format yet.

**Comment by azemrani** [comment]
Thanks for the guidance. Is there anyway to convert Prophesee dat files to the formats supported by jAER?

**Comment by tobidelbruck** [comment]
sorry for late answer. The simplest route is to convert to text CSV format, which jaer can read natively.  I don't know anything about prophesee format or of tool to do this but it must be possible.

Then in jAER add the AEChip class [DVS1280x720SD](https://github.com/SensorsINI/jaer/blob/master/src/ch/unizh/ini/jaer/chip/retina/DVS1280x720SD.java)

![DVS1280x720SD](https://github.com/user-attachments/assets/a1af83da-1051-4222-b585-d13e866af31a)


See [Data file formats in jAER user guide](https://docs.google.com/document/d/1fb7VA8tdoxuYqZfrPfT46_wiT1isQZwTHgX8O22dJ0Q/edit?tab=t.0#bookmark=id.9e7qp8ppuu4c) and [YouTube video Playing CSV files in jAER](https://www.youtube.com/watch?v=I5jdMzXWrbU)
