### ISSUE TITLE
question about usage

### ISSUE THREAD

**Issue by xiaozibuqi** [SensorsINI/jaer#51]
For denoising algorithm, is there any implementation in other language like python?Because I want to experiment on my own dataset

**Comment by tobidelbruck** [comment]
I don't know of any open set of python denoising methods.

If you implement your method in jAER using a subclass of 
AbstractNoiseFilter you can see the live ROC curve and compare with 
other jAER denoising implementations on any jAER recording, including 
those that are saved as CSV files. See DND21 
https://sites.google.com/view/dnd21

**Comment by tobidelbruck** [comment]
inactivity
